### ISSUE TITLE
依存関係を修正してrosdep installを動作させる

### ISSUE THREAD

**Issue by ShotaAk** [SSL-Roots/consai2r2#17]
https://github.com/SSL-Roots/consai2r2/blob/master/consai2r2_sender/package.xml

**Comment by MiraiHattori** [comment]
ubuntu 18.04に関しては
Protobufとなっている部分をprotobuf-devに変えたら現状の部分のビルドが通りました．

dockerコンテナ内の作業で申し訳ないのですが，
root@future731-ThinkPad-T450:/userdir# rosdep db | grep protobuf
protobuf -> libprotobuf10
protobuf-dev -> libprotobuf-dev protobuf-compiler libprotoc-dev
python-protobuf -> python-protobuf

となっており，このうちprotobuf-devのみをpackage.xmlに入れたらビルドが通りました．

**Comment by ShotaAk** [comment]
ee80f585037a694f4aee166319cc454f8c749431
にてrosdepを用いたビルドが成功した。
closeする。
