### ISSUE TITLE
grSimのRobot Statusを受信したい

### ISSUE THREAD

**Issue by spiralray** [SSL-Roots/consai2r2#25]
grSimにボールセンサの情報を吐き出す機能があり、こちらもCON-SAI上でサポートしていただきたいです。

以下のような構成になると思いますがいかがでしょうか❓

1. 以下のようなロボットの状態を表すメッセージRobotStatus.msgを作成
```
uint8 robot_id
bool ball_sensor
```
2. consai2r2_receiverにsim_status_receiverノードを追加

**Comment by ShotaAk** [comment]
お、存在を知らなかったです！取り入れねば

**Comment by ShotaAk** [comment]
参考:
https://github.com/RoboCup-SSL/grSim/blob/master/src/proto/messages_robocup_ssl_robot_status.proto

**Comment by ShotaAk** [comment]
#58 で対応しました。
