### ISSUE TITLE
consai2r2_teleop/include/visibility_control.hは公式のものに置き換えるべき

### ISSUE THREAD

**Issue by HansRobo** [SSL-Roots/consai2r2#38]
https://github.com/ros/class_loader/blob/ros2/include/class_loader/visibility_control.hpp

公式のものが提供されているのでconsai2r2で保持するのではなくそちらを使うべき．

`/opt/ros/dishing/include/class_loader/visibility_control.hpp`の存在は確認済み

**Comment by zohar0729** [comment]
今から作業します

**Comment by zohar0729** [comment]
作業完了しました

**Comment by ShotaAk** [comment]
visibility_control.hはパッケージごとに用意するようです。
そのため、visibility_control.hはconsai2_teleop内のものを使いたいです。

https://github.com/ros2/ros2/issues/37

(１つにまとめる仕組みが欲しい！っていう意見もあるみたいですが、
大元のgccもprefixを変えて使えって書いてますからね。。。)
https://github.com/ament/ament_cmake/issues/164

**Comment by ShotaAk** [comment]
@HansRobo @zohar0729 上記理由より、本件と#39 をクローズしても良いですか？

**Comment by HansRobo** [comment]
問題ないです

**Comment by MiraiHattori** [comment]
https://discourse.ros.org/t/add-visibility-control-h-to-the-api-as-standard-usage/11681/4

**Comment by MiraiHattori** [comment]
メモです．
windowsでは各プロジェクトごとにないと本当に困るようです．

> The trouble comes when you want library A to depend on library B. In that case, you need to mark the symbols of library B as dllimport (so library A can call them), but you need to mark the public symbols of library A as dllexport. So you can’t just have one set of macros to accomplish this. This is why there are per-project macros.

**Comment by zohar0729** [comment]
はい、閉じてもらって大丈夫です、すみません
