### ISSUE TITLE
receiverでロボットからの情報を受け取る

### ISSUE THREAD

**Issue by MiraiHattori** [SSL-Roots/consai2r2#42]
https://github.com/RoboCup-SSL/grSim/blob/5e4dc8828be05fe76dbcdb118e385a9eb254219f/src/sslworld.cpp#L542

grSimの30011/30012ポートから，ロボットがボールに触れている，
ロボットがボールをキックしているというような情報が伝わるようです．
実機の場合も，実機からフィードバックがあるとworldobserverカルマンフィルタに統合できうるなどのメリットもあるので，インターフェースがあると良さそうだと思っています．

**Comment by spiralray** [comment]
#25

**Comment by ShotaAk** [comment]
#25 と同じ内容なのでクローズします。
