### ISSUE TITLE
Cannot import hoge_pb2.py from Python Packages

### ISSUE THREAD

**Issue by spiralray** [SSL-Roots/consai2r2#43]
referee_wrapper実装しようとして思い出しました。

ROS2のpythonパッケージではcmakeは使用ないため、現状の.protoファイルを直接インストールする方法だと、protoから生成されたpythonスクリプトをimportする術が無くなってしまいます。

1つの解決策として以下のような方法があり、protobufのファイルを一括管理できるため現状のファイル構成よりも便利だと考えています。

- `.proto`ファイルを全てconsai2r2_protobufパッケージにまとめる。
- 各パッケージはそこconsai2r2_protobufパッケージからinclude或いはimportする

**Comment by spiralray** [comment]
[rclpy](https://github.com/ros2/rclpy/)の実装を参考にしたら、cmake使いながらpythonを使用することはできそうですね。
ただ、pythonスクリプトを置く場所が…

**Comment by spiralray** [comment]
#44 の実装はいかがでしょうか。

**Comment by ShotaAk** [comment]
読みやすさだと、consai2r2_protobufにまとめたほうがいいですね:+1:

**Comment by ShotaAk** [comment]
#44 でconsai2r2_protobufパッケージを作成しました。クローズします。
